In [1]:
## Questions:

## 1. Create a 1D array of first five multiples of 6.
## 2. Convert the 1D array created in Q1 to 3D, and display the number of dimensions of the latter.
## 3. Create a 2D array where first 5 prime numbers occupy the 1st dimension & the first 5 composite numbers in the 2nd 
##    dimension.
## 4. From the array created in Q3, retrieve the last element from 2nd dimension.
## 5. Retrieve the 2nd, 3rd and 4th elements from both dimensions of the 2D array created in Q3.
## 6. Display the data type of the array created in Q1, and change it to float.
## 7. Create a 1D array of twelve zeros and reshape it to a 2D array of shape (3,4).
## 8. Flatten the 2D array that you created in the previous question back to 1D.
## 9. Consider an array [24,45,67,90,123,367]. Find the indexes where the values are even.
## 10. Create two arrays, one with first 5 odd numbers and the other with first 5 even numbers. 
##     Then concatenate both the arrays along columns.
## 11. Subtract the even number array from the odd number array created in Q10.
## 12. Create two matrices of the squares and cubes of first 4 natural numbers, and perform matrix multiplication. 
##     Also, obtain the transpose of the matrix resulting from the multiplication.

In [3]:
##1.Create a ndarray of first five multiples of 6.
import numpy as np
arr=([6,12,18,24,30])
print(arr)

[6, 12, 18, 24, 30]


In [4]:
##2.Convert the 1D array created in Q1 to 3D, and display the number of dimensions of the latter.
e= np.array(arr,ndmin=3)
print(e)
print("number of dimensions:" , e.ndim)

[[[ 6 12 18 24 30]]]
number of dimensions: 3


In [5]:
## 3. Create a 2D array where first 5 prime numbers occupy the 1st dimension & the first 5 composite numbers in the 2nd 
##    dimension.
arr2=np.array([[2,3,5,7,11],[4,6,8,9,10]])
print(arr2)

[[ 2  3  5  7 11]
 [ 4  6  8  9 10]]


In [6]:
## 4. From the array created in Q3, retrieve the last element from 2nd dimension.
print(arr2[1,-1])

10


In [7]:
## 5. Retrieve the 2nd, 3rd and 4th elements from both dimensions of the 2D array created in Q3.
print(arr2[0:2, 1:4])

[[3 5 7]
 [6 8 9]]


In [8]:
## 6. Display the data type of the array created in Q1, and change it to float.
arr=np.array([6,12,18,24,30])
print(arr.dtype)

new_arr=arr.astype(float)
print(new_arr.dtype)

int32
float64


In [9]:
## 7. Create a 1D array of twelve zeros and reshape it to a 2D array of shape (3,4).
arr3=np.array([0,0,0,0,0,0,0,0,0,0,0,0])
print("1d array dim:",arr3.ndim)

neew_arr=arr3.reshape(3,4)
print("2d array: " , neew_arr)
print("2d array dim :",neew_arr.ndim)

1d array dim: 1
2d array:  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
2d array dim : 2


In [10]:
## 8. Flatten the 2D array that you created in the previous question back to 1D.
new_arr=neew_arr.reshape(-1)
print(new_arr)

[0 0 0 0 0 0 0 0 0 0 0 0]


In [13]:
## 9. Consider an array [24,45,67,90,123,367]. Find the indexes where the values are even.
arr_even=np.array([24,45,67,90,123,367])
a=np.where(arr_even%2==0)
print(a)

(array([0, 3], dtype=int64),)


In [14]:
## 10. Create two arrays, one with first 5 odd numbers and the other with first 5 even numbers. 
##     Then concatenate both the arrays along columns
arr_odd=np.array([1,3,5,7,9])
arr_even1=np.array([2,4,6,8,10])
a=np.vstack((arr_odd,arr_even1))

print(a)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [16]:
## 11. Subtract the even number array from the odd number array created in Q10
arr_sub=np.subtract(arr_odd,arr_even1)
print(arr_sub)

[-1 -1 -1 -1 -1]


In [20]:
## 12. Create two matrices of the squares and cubes of first 4 natural numbers, and perform matrix multiplication. 
##     Also, obtain the transpose of the matrix resulting from the multiplication
arr1=np.array([[1,4],[9,16]])
arr2=np.array([[1,8],[27,64]])
arr3=np.dot(arr1,arr2)
print("multiplication:\n",arr3)
print("transpose:\n", arr3.T)

multiplication:
 [[ 109  264]
 [ 441 1096]]
transpose:
 [[ 109  441]
 [ 264 1096]]


In [ ]:
n=10
n1=[]
n2=[]
for i in range(2,n+1):
    for j in range(2,int(i**0.5)+1):
        
        if i%j==0:
            n1.append(i)
            break
    else:
            n2.append(i)
          
print(n1)
print(n2)
import numpy as np
n1=np.array(n1)
n2=np.array(n2)
y=np.array([n1,n2])
print(y)

In [ ]:
# Part 2 Questions:

# 1.  Write a NumPy program to create a null vector of size 10 and update sixth value to 11.
# [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
# Update sixth value to 11
# [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

# 2.  Write a NumPy program to convert a list and tuple into arrays. 
# List to array:
# [1 2 3 4 5 6 7 8]
# Tuple to array:
# [[8 4 6]
# [1 2 3]]

# 3. Write a NumPy program to find the real and imaginary parts of an array of complex numbers. 
# Expected Output:
# Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
# Real part of the array:
# [ 1. 0.70710678]
# Imaginary part of the array:
# [ 0. 0.70710678]

# 4. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2. 
# Expected Output:
# Array1: [ 0 10 20 40 60 80]
# Array2: [10, 30, 40, 50, 70, 90]
# Set difference between two arrays:
# [ 0 20 60 80]

# 5. a = np.array([x for x in range(27)]) - convert this 1-D to a 3-D array

# 6. Convert the following array into a boolean and display the ouput
#    a = np.array([[1, 0, 0],
#               [1, 1, 1],
#               [0, 0, 0]])

# 7. Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

# 8. From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match:
#    a = np.array([1,2,3,4,5])
#    b = np.array([1,3,2,4,5]) 
    
# 9. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

# 10. Following is the provided numPy array. Return array of items by taking the third column from all rows:
#     sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
    
# 11.  Return array of odd rows and even columns from below numpy array
# sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
# [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

# 12. Split the array into four equal-sized sub-arrays:
# a = [[10 11 12]
#  [13 14 15]
#  [16 17 18]
#  [19 20 21]
#  [22 23 24]
#  [25 26 27]
#  [28 29 30]
#  [31 32 33]]

# 13. Replace all odd numbers in the given array with -1:
#     arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 14. Find the positions of:
#     elements in x where its value is more than its corresponding element in y, and
#     elements in x where its value is equals to its corresponding element in y.
#     x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
#     y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

# 15. Convert a 1-D array into a 2-D array with 3 rows
#     arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
    
# 16. Extract the first four columns of this 2-D array
#     arr = np.arange(100).reshape(5,-1)


In [42]:
#1.
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [41]:
#2.
y=[1 ,2, 3, 4, 5, 6, 7, 8]
array_1=np.array(y)
type(array_1)

numpy.ndarray

In [44]:
#3.
x=[ 1.00000000+0.j, 0.70710678+0.70710678j]
print('real part of the array',np.real(x))
np.imag(x)

real part of the array [1.         0.70710678]


array([0.        , 0.70710678])

In [ ]:
#4. 
Array1= [ 0, 10, 20, 40, 60, 80]
Array2=[10, 30, 40, 50, 70, 90]
np.setdiff1d(Array1, Array2)

In [33]:
#5.
a = np.array([x for x in range(27)])

o = a.reshape((3,3,3))

print(o)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
#6.


In [32]:
#7.
array1=np.arange(0,100,2)
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [23]:
#8.
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5]) 
np.where(a==b)

(array([0, 3, 4], dtype=int64),)

In [ ]:
#9.
print("Creating 5X2 array using numpy.arange")
sampleArray = numpy.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

In [ ]:
#10.

In [ ]:
#11. 
import numpy

sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of odd rows and even columns")
newArray = sampleArray[::2, 1::2]
print(newArray)

In [22]:
#12.
a = np.array([[10, 11, 12],
 [13, 14, 15],
[16, 17 ,18],
[19, 20, 21],
[22, 23, 24],
[25, 26, 27],
[28, 29, 30],
[31, 32, 33]])
np.split(a,4)

[array([[10, 11, 12],
        [13, 14, 15]]), array([[16, 17, 18],
        [19, 20, 21]]), array([[22, 23, 24],
        [25, 26, 27]]), array([[28, 29, 30],
        [31, 32, 33]])]

In [18]:
#13.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1] = -1 
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
#14.
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(np.where(x>y))
print(np.where(x==y))

(array([1, 2, 4, 5, 6, 7, 8, 9], dtype=int64),)
(array([0], dtype=int64),)


In [12]:
#15.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
#16.
import numpy as np
arr = np.arange(100).reshape(5,-1)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [10]:
arr[:,[0,1,2,3]]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])